name: Test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  test:
    name: Test
    strategy:
      matrix:
        php: [ "7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2" ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          extensions: mbstring, pcre
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --no-progress --no-interaction --no-ansi

      - name: Test
        run: composer check
